name: Build Android APK Only

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # ✅ 修正：keystore 放到 app/ 目录下
      - name: Generate debug keystore
        run: |
          cd simple_live_app/android/app
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          cd ..
          echo "storeFile=debug.keystore" > key.properties
          echo "storePassword=android" >> key.properties
          echo "keyPassword=android" >> key.properties
          echo "keyAlias=androiddebugkey" >> key.properties

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk

      - run: echo "✅ Android build done."
