name: Build Android APK Only

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:
          ref: master

      # 设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      # 设置Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # 更新Flutter的packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 打包APK（不签名，直接生成）
      - name: Build APK
        run: |
          cd simple_live_app
          flutter build apk --release --split-per-abi

      # 上传APK至Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk

      # 完成
      - run: echo "✅ Android build done."
